### ISSUE TITLE
MenuLibre not available in Debian Wheezy (stable)

### ISSUE THREAD

**Issue by erm** [gottcode/xfce4-whiskermenu-plugin#104]
It may be a good idea to include some information about alternative menu editors (such as alacarte) that may need to be set on distributions that do not possess a menulibre package. Right now when a menu editor command isn't available, the "Edit Applications" option is simply disabled and that could be confusing for some people. On Debian Wheezy (stable), for example, there is no menulibre package in the stable repositories or backports, but alacarte does exist and works fine as a replacement.

**Comment by gottcode** [comment]
Each distro can package a default settings file that uses something else for editing the applications menu, and if Debian has a generic "applications editor" symlink like they do for "terminal editor" and whatnot, they could use that instead of menulibre.

Also, menulibre is in Debian Jessie, which is *supposed* to become Debian stable later this year. In my view, if a distro doesn't package menulibre, it is their responsibility to set the default to something else. That is the purpose of a distro, after all, to make all of the apps work together.

I suppose I could add a default settings file to the Debian package I maintain on the OBS, and set it to use alacarte. I don't think this belongs in upstream Whisker Menu, though.

**Comment by jristz** [comment]
Maybe let that field blank is a more generic solution?
menulibre is not available in main arch repo and they thing is upstream responsability to keep thing as generic as posssible as they keep it as vanilla as possible too.

**Comment by gottcode** [comment]
Leaving it blank means that users won't be able to edit their menu at all unless they open the preferences of Whisker Menu and specify a menu editing app. Generic, sure, in that every new user gets a bad first experience. :)

The basic problem is that there is no official menu editing application for Xfce. I suppose that alacarte is packaged by more distros than menulibre, but it doesn't seem to work that well with Xfce (in fact, it doesn't work at all for me--changes never show up in the Xfce menus).

**Comment by jristz** [comment]
But ther same bad experience can get for installing the app and run the edditor and not work because is pointing to something not installed (or even not available in the distro) in they system.

This is something more complex than what look because unles a autodetect mechanism is added to whiskler any ther solution could ended in this problem anyway.
