### ISSUE TITLE
[v.1.4.2] [ubuntu 14.10] Menu breaks after reboot, icon turns into a white rectangle

### ISSUE THREAD

**Issue by hashworks** [gottcode/xfce4-whiskermenu-plugin#105]
Often after a reboot the whisker menu icon turns into a white rectangle, resulting in it beeing unusable. It then doesn't react on xfce4-popup-whiskermenu or left/right click. This happens on the default configuration as well.

The only way to fix this is to remove it from the xfce4-panel and add it again, losing all previous settings.

I haven't found any log information in /var/log regarding this issue.

**Comment by gottcode** [comment]
I have only ever encountered this bug in Xubuntu, and even then it has been awhile. For me it just fixed itself one day, so I have not been able to figure out what is going on. Rebooting the panel (running <tt>xfce4-panel -r</tt> in a terminal) made it work for me when it was starting as a gray rectangle, but that doesn't seem to work for all users.

**Comment by hashworks** [comment]
Rebooting the panel works for me.
I guess I'll launch `xfce4-panel -r` on boot for now.

**Comment by tliron** [comment]
The issue seems to be the size of the icon used. I can confirm that when I use 64x64 PNGs the problem has disappeared for me: I tested this on multiple machines.

The bug appeared (intermittently) for me when I was using SVGs, too.

My guess is that this is a race condition: possibly if the image needs to take even a little bit of time for resizing/rendering, then it is exactly too much time before the icon is rendered. I wonder if this can be solved by asynchronously displaying the icon only after it finishes loading?

Here is where I found the solution:
http://ubuntuforums.org/showthread.php?t=2222094

For reference, here are other mentions of the problem:
https://forum.manjaro.org/index.php?topic=16199.0
https://bugs.launchpad.net/ubuntu/+source/xfce4-whiskermenu-plugin/+bug/1391309

**Comment by gottcode** [comment]
Sadly, that is not the base cause. At least, not the cause for everybody. I have talked to some users where this is happening and they are using small icons. When this bug happened for me, I was using the default Xubuntu icon.

The icon is rendered in a different manner in the git version that will become the next feature release. Are you comfortable building the plugin from source to see if it is solved for you when using a large image for the icon?

**Comment by tliron** [comment]
Yes, I am very happy to help you test... But it is difficult due to this bug appearing only sometimes. I think the best bet is to push out the fix and see if it solves things for users.

Of course, it would be ideal if you could find a way to reliably reproduce the bug. Maybe try a very, very large image?

**Comment by gottcode** [comment]
Except that this is happening for users who are using 22px icons, so it can't be the sole cause of the bug. I will push out a fix as soon as I identify and fix the root cause.
